### ISSUE TITLE
Send Fail on STM32F407VE

### ISSUE THREAD

**Issue by bdamarjati** [nopnop2002/Arduino-STM32-CAN#53]
i am using STM32F407VE discovery board with F_CPU 168MHZ, and SN65HVD230 CAN for the transceiver trying to send message from CAN1 (PD0, PD1) to CAN2(PB12,PB13) and get send fail output...
![Screenshot 2023-02-10 114332](https://user-images.githubusercontent.com/75431783/218002790-91d63326-a790-4a85-a9f8-17922538cb0c.png)

i am pretty sure the wiring is correct and there aren't any problem with CAN transceiver module, i also have changed the bit timing but still the same output, any solution or idea on whats the problem i have?

**Comment by nopnop2002** [comment]
If the transmission fails, these are the possible causes.   
- There is no receiving app on CanBus.
- The speed does not match the receiver.
- There is no terminating resistor on the CanBus.
- There are three terminating resistors on the CanBus.
- The resistance value of the terminating resistor is incorrect.
- 3.3V transceiver and 5V transceiver are mixed.   
 +1V Ground Shift using Split Termination.   
 Check [here](http://www.ti.com/lit/an/slla337/slla337.pdf).   
- Stub length in CAN bus is too long.   
 Though the ISO11898 Standard specifies a maximum bus length of 40m and maximum stub length of 0.3m at 1Mbps.
 See [here](https://e2e.ti.com/support/interface-group/interface/f/interface-forum/378932/iso1050-can-bus-stub-length).   
- Noise effects.   
 It occurs when the wire cable is thin or wire cable is crossing.   
 It is preferable to use wires that are noise-proof.   

----

Arduino core support for STM32 based boards uses different clock frequencies depending on the Board Part Number.
BlackPill & BluePill use 72Mhz.
Generic F103 board use 64Mhz instead of 72Mhz.

You can use the F_CPU macro to check the actual frequency
I don't have an STM32F407VE discovery board, but this frequency may not be 168MHZ.
Try building with these.
genericSTM32F407xxxx
black_f407xx

**Comment by bdamarjati** [comment]
i already double check the frequency, and it was 168mhz... i also change the clock to 72mhz the same as bluepil and still get send fail output...

i try the connection using bluepil it was running well, so i think there aren't any problem whatsoever in the conection and the receiver side

may i know what clock speed you use for the F407 one? maybe the problem was on the cpu clock

**Comment by bdamarjati** [comment]
this is the STM32F407VE that i used
![20230210_170005.jpg](https://user-images.githubusercontent.com/75431783/218062253-2ba44857-1e43-4205-a367-bf45e2e91a04.jpg)

**Comment by nopnop2002** [comment]
Are you using the Arduino IDE?
Or PlatformIO are you using?

**Comment by bdamarjati** [comment]
im using arduino ide with stm32 core that you included here as the reference

**Comment by nopnop2002** [comment]
i want to see your build options
This is my build option.
![f407](https://user-images.githubusercontent.com/6020549/218073645-f3b6dc1a-22fc-45ea-8255-58d6f945788c.JPG)

**Comment by bdamarjati** [comment]
mine are the same as yours but using serial as the upload method

**Comment by nopnop2002** [comment]
it's definitely a wiring issue.
In your picture it looks like the CAN bus stub length is long

Can packets from other nodes be received correctly?

**Comment by bdamarjati** [comment]
the initializing is success but the transmitting is the issue, so i think the board can detect the transceiver module but fail when sending/receiving message

i use awg 24 cable for the stub, it's roughly 20cm long

**Comment by bdamarjati** [comment]
i try to receive packet from other can bus device with the same baudrate, and there aren't any message receive on STM32F407VE
here's my serial monitor on arduino (left one is receiver and the right one is transmitter)
![image](https://user-images.githubusercontent.com/75431783/218080299-45c50354-e92d-4c59-b7ec-e6dc0a284af3.png)

**Comment by nopnop2002** [comment]
One hint is that the sender did not detect the transmission failure.
A sender detects a send failure when it cannot send.
Try this with F103.

**Comment by bdamarjati** [comment]
oh hi thank for the reply, i already checked using F103 send to F407, the output is Send Fail on F103 and blank on F407

the thing is, i check the wiring using F103 send to Arduino Nano is running well

any idea about this issue?

**Comment by nopnop2002** [comment]
There have been many reports of F103 sending failures in the past.
Most of them can receive but fail to send.

AtMega328 uses a 5V transceiver.
STM32 uses a 3.3V transceiver.
This difference is related to the value of the terminating resistor.

Transmission failures on F103 were mostly due to termination resistors or cable quality.


If the transmission fails, these are the possible causes.   
- There is no receiving app on CanBus.
- The speed does not match the receiver.
- There is no terminating resistor on the CanBus.
- There are three terminating resistors on the CanBus.
- The resistance value of the terminating resistor is incorrect.
- 3.3V transceiver and 5V transceiver are mixed.   
 +1V Ground Shift using Split Termination.   
 Check [here](http://www.ti.com/lit/an/slla337/slla337.pdf).   
- Stub length in CAN bus is too long.   
 Though the ISO11898 Standard specifies a maximum bus length of 40m and maximum stub length of 0.3m at 1Mbps.
 See [here](https://e2e.ti.com/support/interface-group/interface/f/interface-forum/378932/iso1050-can-bus-stub-length).   
- Noise effects.   
 It occurs when the wire cable is thin or wire cable is crossing.   
 It is preferable to use wires that are noise-proof.   

I changed the single wire to twisted wire. It's fixed.   
![CAN-SendFail](https://user-images.githubusercontent.com/6020549/185782335-66d1f534-5220-40a2-aee9-5d4a438c59a0.jpg)

**Comment by bdamarjati** [comment]
okay thank for the reply, i managed to make it work somehow

turns out it was the can speed, possibly because of the signal frequency on F407 is higher or some kind of thing, so i used half can bus speed of the receiver

e.g: Arduino (receiver) using 500kbps on F407 (sender) using 250kbps and vice versa in order to make the transmission work, at least in my case

**Comment by bdamarjati** [comment]
mine's already work so i think i'm going to close the issue now

thanks
