### ISSUE TITLE
how is Serial and CAN being used simultaneously in STM32F103?

### ISSUE THREAD

**Issue by i-make-robots** [nopnop2002/Arduino-STM32-CAN#54]
STM32F103 manual says:

In low, medium-, high- and XL-density devices the USB and CAN share a dedicated 512-byte SRAM memory for data transmission and reception, and so they cannot be used concurrently (the shared SRAM is accessed through CAN and USB exclusively). The USB and CAN can be used in the same application but not at the same time.

so... how do I make sure they stay non-concurrent?

**Comment by nopnop2002** [comment]
>The USB and CAN can be used in the same application but not at the same time.

Yes, that's right.

STM32F103 can use a Virtual COM port.
If you enable Virtual COM port, you can use the USB port as a serial port.
But Basic Extended CAN(BxCan) and Virtual COM port cannot be used at the same time.
If you want to use a Serial object, you need to use a USB-UART conversion module.
Note:
For STM32F405/407, BxCan and Virtual COM port can be used at the same time.
The reason the F103 chip cannot use BxCan and Virtual COM port at the same time is because they share memory buffers.

>how do I make sure they stay non-concurrent?

they stay non-concurrent if CAN communication works correctly

**Comment by i-make-robots** [comment]
Thank you for the advice.  Is there a chip in the 48 pin package that would work?  I have been using STM32F103 which is 48 pin.
The STM32F411 looked good but it does not have CAN.  I am struggling to find the right match.

**Comment by nopnop2002** [comment]
Try this.
Basic Extended CAN(BxCan) and Virtual COM port can be used at the same time.

https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f303

https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f405

https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f407


I bought the F303 a long time ago. 

You can use this page to find the 48pin package
F302/303/328/334/357/373/378 has a 48-pin package.
https://www.stmcu.jp/stm32/stm32f3/

![stm32f3](https://user-images.githubusercontent.com/6020549/221760018-f22554c2-8ed4-4e88-b899-d18e23c92d20.jpg)


It's hard to find a 48-pin package for the F405 and F407.

https://www.stmcu.jp/stm32/stm32f4/
